-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    "Id" integer NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Password" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."JobSeekers"
(
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "NationalityId" character(11) NOT NULL,
    "BirthdayDate" date NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Employers"
(
    "Id" integer NOT NULL,
    "CompanyName" character varying(60) NOT NULL,
    "WebSite" character varying(100) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SystemPersonels"
(
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."JobPositions"
(
    "Id" integer NOT NULL,
    "PositionName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."EmailVerification"
(
    "Id" integer NOT NULL,
    "Confirm" boolean NOT NULL,
    "ConfirmDate" date NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."PhoneNumbers"
(
    "Id" integer NOT NULL,
    "PhoneNumber" character(11) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SystemVerification"
(
    "Id" integer NOT NULL,
    "SystemPersonId" integer NOT NULL,
    "Confirm" boolean NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."SystemPersonels"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."PhoneNumbers" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."EmailVerification" ("Id")
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."EmailVerification" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."SystemVerification" ("Id")
    NOT VALID;

END;