CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING(50) NOT NULL,
	password character varying(20),
	constraint pk_users primary key(id),
	constraint uc_users_email unique(email)
);
create table public.employers(
	id INT not null,
	company_name character varying(50) not null,
	web_site character varying(50) not null,
	constraint pk_employers primary key(id),
	constraint fk_employers_users foreign key(id) references public.users(id)
);
create table public.employees(
	id int not null,
	first_name character varying(50) not null,
	last_name character varying(50) not null,
	constraint pk_employees primary key(id),
	constraint fk_employees_users foreign key(id) references public.users(id)
);
create table public.job_seekers(
	id int not null,
	first_name character varying(50) not null,
	last_name character varying(50) not null,
	nationality_id character(11) not null,
	birthday_date int not null,
	constraint pk_job_seekers primary key(id),
	constraint fk_job_seekers_users foreign key(id) references public.users(id),
	constraint uc_job_seekers_nationality_id unique(nationality_id)
);
create table public.phone_numbers(
	id int not null,
	phone_number character(11) not null,
	constraint pk_phone_numbers primary key(id),
	constraint fk_phone_numbers_employers foreign key(id) references public.employers(id),
	constraint uc_phone_number unique(phone_number)
);
create table public.email_verifications(
	id int not null,
	confirm boolean not null,
	confirm_date character varying(11) not null,
	constraint pk_email_verifications primary key(id),
	constraint fk_email_verifications_employers foreign key(id) references public.employers(id),
	constraint fk_email_verifications_job_seekers foreign key(id) references public.job_seekers(id)
);
create table public.system_verifications(
	id int not null,
	system_person_id int,
	confirm boolean not null,
	constraint pk_system_verifications primary key(id),
	constraint fk_system_verifications_employers foreign key(id) references public.employers(id)
);
create table public.job_positions(
	id int GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	position_name character varying(30) not null,
	constraint pk_job_positions primary key(id),
	constraint uc_job_positions unique(position_name)
);

create table public.cities(
id smallint generated by default as identity(INCREMENT 1 start 1 minvalue 1),
city_name character varying(16) not null,
constraint pk_cities primary key(id)
);

create table public.job_postings(
id INT generated by default as identity(increment 1 start 1 minvalue 1) not null,
employer_id INT not null,
job_position_id INT not null,
city_id SMALLINT not null,

min_salary money,
max_salary money,
open_position int not null,
job_description character varying(500) not null,
application_deadline character varying(11) not null,

constraint pk_job_postings primary key(id),
constraint fk_job_postings_employers foreign key(employer_id) references public.employers(id),
constraint fk_job_postings_job_positions foreign key(job_position_id) references public.job_positions(id),
constraint fk_job_positngs_cities foreign key(city_id) references public.cities(id)

);

